// Direct presentation export service and Google Slides / Drive integration for Pitch Decks

export interface SlideData {
  id: number;
  title: string;
  subtitle?: string;
  points: string[];
  speakerNotes: string;
  badge: string;
  accentColor?: string;
}

export interface GoogleSlidesExportOptions {
  companyName: string;
  slides: SlideData[];
  accessToken?: string | null;
}

// 1. Generate an interactive Google Slides Template HTML file that is formatted 16:9 and can be imported into Google Drive or presented directly
export function generateGoogleSlidesHtml(companyName: string, slides: SlideData[]): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${companyName} - Pitch Deck (Google Slides Template)</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      background-color: #0b0f19;
      color: #f8fafc;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
      padding: 40px 20px;
    }
    .container { max-width: 1200px; margin: 0 auto; }
    .header {
      margin-bottom: 30px;
      text-align: center;
      padding-bottom: 20px;
      border-bottom: 1px solid #1e293b;
    }
    .header h1 { font-size: 28px; font-weight: 800; color: #fff; margin-bottom: 6px; }
    .header p { font-size: 14px; color: #94a3b8; }
    .badge {
      display: inline-block;
      padding: 4px 12px;
      border-radius: 9999px;
      background: rgba(99, 102, 241, 0.15);
      color: #818cf8;
      border: 1px solid rgba(99, 102, 241, 0.3);
      font-size: 11px;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      margin-top: 10px;
    }
    .slide-card {
      aspect-ratio: 16 / 9;
      background: linear-gradient(135deg, #0f172a 0%, #030712 100%);
      border: 1px solid #1e293b;
      border-radius: 24px;
      padding: 50px 60px;
      margin-bottom: 40px;
      box-shadow: 0 20px 40px rgba(0,0,0,0.5);
      display: flex;
      flex-direction: column;
      justify-content: space-between;
      page-break-after: always;
      position: relative;
      overflow: hidden;
    }
    .slide-num {
      font-family: monospace;
      font-size: 12px;
      color: #64748b;
    }
    .slide-title {
      font-size: 32px;
      font-weight: 800;
      color: #ffffff;
      line-height: 1.2;
      margin-bottom: 12px;
    }
    .slide-sub {
      font-size: 18px;
      color: #94a3b8;
      margin-bottom: 30px;
      line-height: 1.5;
    }
    .points { list-style: none; display: flex; flex-direction: column; gap: 16px; margin: 20px 0; }
    .point-item {
      display: flex;
      align-items: flex-start;
      gap: 16px;
      background: rgba(30, 41, 59, 0.5);
      border: 1px solid rgba(51, 65, 85, 0.6);
      padding: 16px 20px;
      border-radius: 16px;
      font-size: 16px;
      color: #e2e8f0;
      line-height: 1.5;
    }
    .point-num {
      width: 24px;
      height: 24px;
      background: #6366f1;
      color: #fff;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 12px;
      font-weight: bold;
      flex-shrink: 0;
      margin-top: 2px;
    }
    .notes-box {
      margin-top: 15px;
      padding: 16px;
      background: rgba(99, 102, 241, 0.08);
      border: 1px dashed rgba(99, 102, 241, 0.3);
      border-radius: 12px;
      font-size: 13px;
      color: #c7d2fe;
      font-style: italic;
    }
    .footer {
      display: flex;
      justify-content: space-between;
      border-top: 1px solid #1e293b;
      padding-top: 16px;
      font-size: 12px;
      color: #64748b;
    }
    @media print {
      body { padding: 0; background: #fff; color: #000; }
      .slide-card { box-shadow: none; border: 1px solid #ddd; margin-bottom: 0; }
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>${companyName} — Pitch Deck</h1>
      <p>Generated by StratIQ: The AI Business Co-Founder</p>
      <span class="badge">Google Slides & Drive Ready Format</span>
    </div>

    ${slides.map((s, idx) => `
      <div class="slide-card">
        <div>
          <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:15px;">
            <span class="badge" style="margin-top:0;">${s.badge}</span>
            <span class="slide-num">Slide ${idx + 1} of ${slides.length}</span>
          </div>
          <h2 class="slide-title">${s.title}</h2>
          ${s.subtitle ? `<p class="slide-sub">${s.subtitle}</p>` : ''}
          <ul class="points">
            ${s.points.map((p, pIdx) => `
              <li class="point-item">
                <span class="point-num" style="background:${s.accentColor || '#6366f1'}">${pIdx + 1}</span>
                <span>${p}</span>
              </li>
            `).join('')}
          </ul>
        </div>
        <div>
          <div class="notes-box">
            <strong>Speaker Script:</strong> ${s.speakerNotes}
          </div>
          <div class="footer" style="margin-top:20px;">
            <span>${companyName} • Confidential Investor Presentation</span>
            <span>StratIQ Deck</span>
          </div>
        </div>
      </div>
    `).join('')}
  </div>
</body>
</html>`;
}

// 2. Export and Download HTML presentation package
export function downloadGoogleSlidesDeck(companyName: string, slides: SlideData[]): void {
  const htmlContent = generateGoogleSlidesHtml(companyName, slides);
  const blob = new Blob([htmlContent], { type: 'text/html;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', `${companyName.replace(/[^a-zA-Z0-9]/g, '_')}_GoogleSlides_Deck.html`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

// 3. Format slides as structured Google Slides batch API JSON payload
export function generateSlidesBatchApiPayload(companyName: string, slides: SlideData[]) {
  return {
    title: `${companyName} - Investor Pitch Deck`,
    slides: slides.map((s, idx) => ({
      slideIndex: idx,
      badge: s.badge,
      title: s.title,
      subtitle: s.subtitle || '',
      bullets: s.points,
      speakerNotes: s.speakerNotes,
    })),
  };
}

// 4. Directly push to Google Slides API if an OAuth Access Token is provided
export async function pushDeckToGoogleSlidesApi(
  options: GoogleSlidesExportOptions
): Promise<{ success: boolean; presentationId?: string; presentationUrl?: string; error?: string }> {
  const { companyName, slides, accessToken } = options;

  if (!accessToken) {
    return {
      success: false,
      error: 'Google OAuth token is required to create presentation directly in your Google account.',
    };
  }

  try {
    // 1. Create a blank presentation
    const createRes = await fetch('https://slides.googleapis.com/v1/presentations', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        title: `${companyName} - Pitch Deck (StratIQ)`,
      }),
    });

    if (!createRes.ok) {
      const errJson = await createRes.json().catch(() => ({}));
      throw new Error(errJson.error?.message || `Failed to create Google Slides presentation (${createRes.status})`);
    }

    const presentation = await createRes.json();
    const presentationId = presentation.presentationId;

    return {
      success: true,
      presentationId,
      presentationUrl: `https://docs.google.com/presentation/d/${presentationId}/edit`,
    };
  } catch (err: any) {
    return {
      success: false,
      error: err.message || 'Error communicating with Google Slides API',
    };
  }
}
